### PR TITLE
Allowed spaces in Column names

### PR DESCRIPTION
**Pull request by Worthy7**

### CODE REVIEW

**Comment by blag001** [comment]
could you make this with ``` ` ``` (mysql quote, and not `'`) for the whole file ? (just patch the sql query around) 
Cause it seem it's actually done more or less ( https://github.com/jonseg/crud-admin-generator/blob/master/src/console.php#L45 ) but if we start on this, it's better to make it everywhere...

**Comment by Worthy7** [comment]
I don't really know how these files work too well, I was just hoping someone else could sort this out.

**Comment by Worthy7** [comment]
I don't really know how these files work, so this will have to wait unless someone else does it.

**Comment by blag001** [comment]
Close this pull request please, as the https://github.com/jonseg/crud-admin-generator/pull/71 is the one to use ;)

**Pull request closed without merging**
